name: Sychar Unit Tests

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  unit-tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"

      - name: "Install Pip dependencies"
        run: |
          python -m pip install pip --upgrade pip
          pip install -r requirements.txt

      - name: "Run tests"
        run: >-
          coverage run -m pytest -v

      - name: "Code coverage report"
        run: >-
          coverage report -m
